catch SQLiteException error code 5: database is locked
In the Market developer console I noticed one exception triggered
(supposedly causing a force close upon sms reception). So this change
tries to catch the exception and it retry a few times.

I can't reproduce on the emulator, maybe some 3rd party app keeps the
db open for too long.

java.lang.RuntimeException: Unable to start receiver com.aa.smsfailfix.SmsReceiver: android.database.sqlite.SQLiteException: error code 5: database is locked
at android.app.ActivityThread.handleReceiver(ActivityThread.java:2821)
at android.app.ActivityThread.access$3200(ActivityThread.java:125)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2083)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:123)
at android.app.ActivityThread.main(ActivityThread.java:4627)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:521)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:858)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
at dalvik.system.NativeStart.main(Native Method)
Caused by: android.database.sqlite.SQLiteException: error code 5: database is locked
at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:158)
at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:114)
at android.content.ContentProviderProxy.update(ContentProviderNative.java:495)
at android.content.ContentResolver.update(ContentResolver.java:707)
at com.aa.smsfailfix.SmsFixup.smsFixup(SmsFixup.java:24)
at com.aa.smsfailfix.SmsReceiver.onReceive(SmsReceiver.java:19)
at android.app.ActivityThread.handleReceiver(ActivityThread.java:2810)
... 10 more